import { useAuth } from "@/_core/hooks/useAuth";
import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { Archive, Package, Pencil, Plus, Search, X } from "lucide-react";
import { FormEvent, useState } from "react";
import { toast } from "sonner";

type CatalogRecord = { id: number; type: "product" | "service"; name: string; description: string | null; category: string | null; unitPriceCents: number; currency: string; archivedAt: Date | null; };
const money = (cents: number, currency: string) => new Intl.NumberFormat("pt-PT", { style: "currency", currency }).format(cents / 100);

export default function Catalog() {
  const { user } = useAuth();
  const utils = trpc.useUtils();
  const [search, setSearch] = useState("");
  const query = trpc.catalog.list.useQuery({ includeArchived: true, query: search }, { enabled: user?.role === "admin" });
  const create = trpc.catalog.create.useMutation({ onSuccess: () => { utils.catalog.list.invalidate(); toast.success("Item adicionado ao catálogo."); } });
  const update = trpc.catalog.update.useMutation({ onSuccess: () => { utils.catalog.list.invalidate(); toast.success("Item atualizado."); } });
  const archive = trpc.catalog.archive.useMutation({ onSuccess: () => utils.catalog.list.invalidate() });
  const [editing, setEditing] = useState<CatalogRecord | null>(null);
  const [showForm, setShowForm] = useState(false);

  if (user && user.role !== "admin") return <DashboardLayout><div className="deco-panel mx-auto max-w-2xl p-10 text-center"><p className="deco-eyebrow">Acesso reservado</p><h1 className="deco-title mt-2 text-4xl">Catálogo administrativo</h1><p className="mt-3 text-muted-foreground">Apenas administradores podem gerir os preços e os itens do catálogo.</p></div></DashboardLayout>;
  function close() { setEditing(null); setShowForm(false); }
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const form = new FormData(event.currentTarget); const rawPrice = String(form.get("price") ?? "0").replace(",", ".");
    const data = { type: String(form.get("type")) as "product" | "service", name: String(form.get("name") ?? "").trim(), description: String(form.get("description") ?? "").trim() || null, category: String(form.get("category") ?? "").trim() || null, unitPriceCents: Math.round(Number(rawPrice) * 100), currency: String(form.get("currency") || "EUR").toUpperCase() };
    if (!Number.isFinite(data.unitPriceCents) || data.unitPriceCents < 0) return toast.error("Indique um preço válido.");
    try { if (editing) await update.mutateAsync({ id: editing.id, data }); else await create.mutateAsync(data); close(); } catch (error) { toast.error(error instanceof Error ? error.message : "Não foi possível guardar o item."); }
  }
  return <DashboardLayout><section className="mx-auto max-w-7xl space-y-7"><header className="flex flex-col justify-between gap-5 border-b border-primary/30 pb-7 sm:flex-row sm:items-end"><div><p className="deco-eyebrow">Oferta comercial</p><h1 className="deco-title mt-2 text-5xl sm:text-6xl">Catálogo</h1><p className="mt-3 text-muted-foreground">Produtos e serviços reutilizáveis nos itens de linha das propostas.</p></div><Button onClick={() => { setEditing(null); setShowForm(true); }} className="h-11 rounded-none bg-primary text-primary-foreground hover:bg-primary/85"><Plus className="mr-2 h-4 w-4" />Novo item</Button></header>
    {showForm && <form onSubmit={submit} className="deco-panel grid gap-4 p-6 md:grid-cols-2"><div className="md:col-span-2 flex items-center justify-between"><div><p className="deco-eyebrow">{editing ? "Editar" : "Criar"}</p><h2 className="deco-title text-3xl">Item do catálogo</h2></div><Button type="button" onClick={close} variant="ghost" className="rounded-none text-primary hover:bg-primary/10 hover:text-primary"><X className="h-4 w-4" /></Button></div><label className="space-y-2 text-sm">Tipo<select name="type" defaultValue={editing?.type ?? "service"} className="flex h-9 w-full border border-input bg-transparent px-3 text-sm"><option value="service">Serviço</option><option value="product">Produto</option></select></label><label className="space-y-2 text-sm">Nome<Input name="name" required defaultValue={editing?.name ?? ""} className="rounded-none" /></label><label className="space-y-2 text-sm">Categoria<Input name="category" defaultValue={editing?.category ?? ""} className="rounded-none" /></label><label className="space-y-2 text-sm">Preço unitário<Input name="price" inputMode="decimal" required defaultValue={editing ? (editing.unitPriceCents / 100).toFixed(2) : ""} className="rounded-none" /></label><label className="space-y-2 text-sm">Moeda<Input name="currency" maxLength={3} defaultValue={editing?.currency ?? "EUR"} className="rounded-none uppercase" /></label><label className="space-y-2 text-sm md:col-span-2">Descrição<Textarea name="description" defaultValue={editing?.description ?? ""} className="min-h-24 rounded-none" /></label><div className="md:col-span-2 flex justify-end gap-3"><Button type="button" variant="outline" onClick={close} className="rounded-none border-primary/50 text-primary hover:bg-primary/10 hover:text-primary">Cancelar</Button><Button type="submit" disabled={create.isPending || update.isPending} className="rounded-none bg-primary text-primary-foreground hover:bg-primary/85">Guardar item</Button></div></form>}
    <div className="deco-panel overflow-hidden"><div className="flex flex-col gap-4 border-b border-primary/25 p-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="deco-eyebrow">Preço e disponibilidade</p><h2 className="deco-title mt-1 text-3xl">Itens ativos e arquivados</h2></div><div className="relative w-full sm:w-72"><Search className="absolute left-3 top-3 h-4 w-4 text-primary" /><Input value={search} onChange={event => setSearch(event.target.value)} placeholder="Pesquisar no catálogo" className="rounded-none pl-9" /></div></div>{query.isLoading ? <div className="p-10 text-center text-muted-foreground">A carregar catálogo…</div> : !query.data?.length ? <div className="p-12 text-center"><Package className="mx-auto h-8 w-8 text-primary" /><h3 className="deco-title mt-4 text-2xl">Sem itens encontrados</h3><p className="mt-2 text-sm text-muted-foreground">Adicione produtos ou serviços para os selecionar nas propostas.</p></div> : <div className="divide-y divide-primary/15">{query.data.map(item => <div key={item.id} className="flex items-center justify-between gap-4 px-6 py-4"><div className="min-w-0"><p className="font-semibold">{item.name}{item.archivedAt && <span className="ml-2 text-xs font-normal uppercase tracking-wider text-muted-foreground">Arquivado</span>}</p><p className="mt-1 text-sm text-muted-foreground">{item.type === "service" ? "Serviço" : "Produto"} · {item.category || "Sem categoria"}</p></div><div className="flex items-center gap-2"><p className="mr-2 font-semibold text-primary">{money(item.unitPriceCents, item.currency)}</p><Button size="icon" variant="ghost" onClick={() => { setEditing(item); setShowForm(true); }} className="rounded-none text-primary hover:bg-primary/10 hover:text-primary"><Pencil className="h-4 w-4" /></Button><Button size="icon" variant="ghost" onClick={() => archive.mutate({ id: item.id, archived: !item.archivedAt }, { onSuccess: () => toast.success(item.archivedAt ? "Item reativado." : "Item arquivado.") })} className="rounded-none text-primary hover:bg-primary/10 hover:text-primary"><Archive className="h-4 w-4" /></Button></div></div>)}</div>}</div>
  </section></DashboardLayout>;
}
