import { useAuth } from "@/_core/hooks/useAuth";
import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { Building2, ImageUp, Save } from "lucide-react";
import { FormEvent } from "react";
import { toast } from "sonner";

export default function Company() {
  const { user } = useAuth();
  const utils = trpc.useUtils();
  const company = trpc.company.get.useQuery(undefined, { enabled: user?.role === "admin" });
  const save = trpc.company.save.useMutation({ onSuccess: () => { utils.company.get.invalidate(); toast.success("Definições da empresa guardadas."); } });
  const uploadLogo = trpc.company.uploadLogo.useMutation({ onSuccess: () => { utils.company.get.invalidate(); toast.success("Logótipo guardado no armazenamento seguro."); } });
  if (user && user.role !== "admin") return <DashboardLayout><div className="deco-panel mx-auto max-w-2xl p-10 text-center"><p className="deco-eyebrow">Acesso reservado</p><h1 className="deco-title mt-2 text-4xl">Definições empresariais</h1><p className="mt-3 text-muted-foreground">Apenas administradores podem alterar a identidade presente nos documentos comerciais.</p></div></DashboardLayout>;
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const value = (name: string) => String(form.get(name) ?? "").trim() || null; const data = { legalName: String(form.get("legalName") ?? "").trim(), tradingName: value("tradingName"), taxId: value("taxId"), email: value("email"), phone: value("phone"), website: value("website"), addressLine1: value("addressLine1"), addressLine2: value("addressLine2"), postalCode: value("postalCode"), city: value("city"), country: value("country"), logoStorageKey: company.data?.logoStorageKey ?? null, logoUrl: company.data?.logoUrl ?? null }; try { await save.mutateAsync(data); } catch (error) { toast.error(error instanceof Error ? error.message : "Não foi possível guardar as definições."); } }
  async function selectLogo(file?: File) { if (!file) return; if (!company.data) return toast.error("Guarde primeiro os dados da empresa."); if (!file.type.startsWith("image/")) return toast.error("Selecione um ficheiro de imagem."); const dataUrl = await new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = reject; reader.readAsDataURL(file); }); try { await uploadLogo.mutateAsync({ filename: file.name, dataUrl }); } catch (error) { toast.error(error instanceof Error ? error.message : "Não foi possível carregar o logótipo."); } }
  return <DashboardLayout><section className="mx-auto max-w-5xl space-y-7"><header className="border-b border-primary/30 pb-7"><p className="deco-eyebrow">Identidade documental</p><h1 className="deco-title mt-2 text-5xl sm:text-6xl">A sua empresa</h1><p className="mt-3 max-w-2xl text-muted-foreground">Estes dados são incluídos automaticamente na pré-visualização, no PDF e no email de cada proposta.</p></header>
    <form onSubmit={submit} className="deco-panel grid gap-5 p-6 md:grid-cols-2"><div className="md:col-span-2 flex items-center gap-3"><Building2 className="h-5 w-5 text-primary" /><div><p className="deco-eyebrow">Dados persistentes</p><h2 className="deco-title mt-1 text-3xl">Informação fiscal e de contacto</h2></div></div><label className="space-y-2 text-sm md:col-span-2">Nome legal<Input required name="legalName" defaultValue={company.data?.legalName ?? ""} className="rounded-none" /></label><label className="space-y-2 text-sm">Nome comercial<Input name="tradingName" defaultValue={company.data?.tradingName ?? ""} className="rounded-none" /></label><label className="space-y-2 text-sm">NIF<Input name="taxId" defaultValue={company.data?.taxId ?? ""} className="rounded-none" /></label><label className="space-y-2 text-sm">Email de contacto<Input type="email" name="email" defaultValue={company.data?.email ?? ""} className="rounded-none" /></label><label className="space-y-2 text-sm">Telefone<Input name="phone" defaultValue={company.data?.phone ?? ""} className="rounded-none" /></label><label className="space-y-2 text-sm md:col-span-2">Website<Input name="website" defaultValue={company.data?.website ?? ""} className="rounded-none" /></label><label className="space-y-2 text-sm md:col-span-2">Morada<Input name="addressLine1" defaultValue={company.data?.addressLine1 ?? ""} className="rounded-none" /></label><label className="space-y-2 text-sm md:col-span-2">Complemento de morada<Input name="addressLine2" defaultValue={company.data?.addressLine2 ?? ""} className="rounded-none" /></label><label className="space-y-2 text-sm">Código postal<Input name="postalCode" defaultValue={company.data?.postalCode ?? ""} className="rounded-none" /></label><label className="space-y-2 text-sm">Cidade<Input name="city" defaultValue={company.data?.city ?? ""} className="rounded-none" /></label><label className="space-y-2 text-sm">País<Input name="country" defaultValue={company.data?.country ?? ""} className="rounded-none" /></label><div className="md:col-span-2 mt-3 flex justify-end"><Button type="submit" disabled={save.isPending} className="h-11 rounded-none bg-primary px-5 text-primary-foreground hover:bg-primary/85"><Save className="mr-2 h-4 w-4" />Guardar definições</Button></div></form>
    <section className="deco-panel p-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><p className="deco-eyebrow">Marca visual</p><h2 className="deco-title mt-1 text-3xl">Logótipo da empresa</h2><p className="mt-2 text-sm text-muted-foreground">É armazenado em S3 e utilizado na pré-visualização e no PDF.</p></div>{company.data?.logoUrl && <img src={company.data.logoUrl} alt="Logótipo atual" className="h-16 max-w-40 object-contain" />}</div><label className="mt-5 inline-flex cursor-pointer items-center border border-primary/50 px-4 py-2 text-sm text-primary transition-colors hover:bg-primary/10"><ImageUp className="mr-2 h-4 w-4" />{uploadLogo.isPending ? "A carregar…" : "Carregar logótipo"}<input type="file" accept="image/*" className="sr-only" disabled={uploadLogo.isPending} onChange={event => selectLogo(event.target.files?.[0])} /></label></section>
  </section></DashboardLayout>;
}
