import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { ArrowLeft, Minus, Plus, Save, Trash2 } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { toast } from "sonner";
import { useLocation } from "wouter";

type DraftLine = { catalogItemId: number | null; title: string; description: string; quantity: number; unitPriceCents: number; discountBps: number; };
type Draft = { title: string; clientId: number; currency: string; taxRateBps: number; globalDiscountBps: number; validUntil: string; publicSharingEnabled: boolean; clientMessage: string; internalNotes: string; paymentTerms: string; downPayment: string; financingTerms: string; commissionTerms: string; eligibilityCriteria: string; catalogAttributes: string; items: DraftLine[]; };
const blank: Draft = { title: "", clientId: 0, currency: "EUR", taxRateBps: 2300, globalDiscountBps: 0, validUntil: "", publicSharingEnabled: true, clientMessage: "", internalNotes: "", paymentTerms: "", downPayment: "", financingTerms: "", commissionTerms: "", eligibilityCriteria: "", catalogAttributes: "", items: [] };
const money = (cents: number, currency: string) => new Intl.NumberFormat("pt-PT", { style: "currency", currency }).format(cents / 100);

export default function ProposalEditor({ id }: { id?: number }) {
  const [, navigate] = useLocation();
  const utils = trpc.useUtils();
  const clients = trpc.clients.list.useQuery();
  const catalog = trpc.catalog.list.useQuery();
  const detail = trpc.proposals.detail.useQuery({ id: id! }, { enabled: Boolean(id) });
  const create = trpc.proposals.create.useMutation({ onSuccess: proposalId => { utils.proposals.list.invalidate(); utils.dashboard.metrics.invalidate(); toast.success("Proposta criada em rascunho."); navigate(`/propostas/${proposalId}`); } });
  const update = trpc.proposals.update.useMutation({ onSuccess: () => { utils.proposals.list.invalidate(); detail.refetch(); toast.success("Rascunho guardado."); } });
  const [draft, setDraft] = useState<Draft>(blank);

  useEffect(() => {
    if (!detail.data) return;
    const { proposal, items, metadata } = detail.data;
    const terms = (metadata?.commercialTerms as Record<string, unknown> | undefined) ?? {};
    const text = (key: string) => String(terms[key] ?? "");
    setDraft({ title: proposal.title, clientId: proposal.clientId, currency: proposal.currency, taxRateBps: proposal.taxRateBps, globalDiscountBps: proposal.globalDiscountBps, validUntil: proposal.validUntil ? new Date(proposal.validUntil).toISOString().slice(0, 10) : "", publicSharingEnabled: proposal.publicSharingEnabled, clientMessage: proposal.clientMessage ?? "", internalNotes: proposal.internalNotes ?? "", paymentTerms: text("paymentTerms"), downPayment: text("downPayment"), financingTerms: text("financingTerms"), commissionTerms: text("commissionTerms"), eligibilityCriteria: text("eligibilityCriteria"), catalogAttributes: text("catalogAttributes"), items: items.map(item => ({ catalogItemId: item.catalogItemId, title: item.title, description: item.description ?? "", quantity: Number(item.quantity), unitPriceCents: item.unitPriceCents, discountBps: item.discountBps })) });
  }, [detail.data]);

  const totals = useMemo(() => { const subtotal = draft.items.reduce((sum, item) => sum + Math.round(item.quantity * item.unitPriceCents) - Math.round(item.quantity * item.unitPriceCents * item.discountBps / 10000), 0); const discount = Math.round(subtotal * draft.globalDiscountBps / 10000); const tax = Math.round((subtotal - discount) * draft.taxRateBps / 10000); return { subtotal, discount, tax, total: subtotal - discount + tax }; }, [draft.items, draft.globalDiscountBps, draft.taxRateBps]);
  const set = <K extends keyof Draft>(key: K, value: Draft[K]) => setDraft(current => ({ ...current, [key]: value }));
  const updateLine = (index: number, values: Partial<DraftLine>) => setDraft(current => ({ ...current, items: current.items.map((item, position) => position === index ? { ...item, ...values } : item) }));
  const addCatalogItem = (catalogItemId: number) => { const item = catalog.data?.find(candidate => candidate.id === catalogItemId); if (!item) return; setDraft(current => ({ ...current, items: [...current.items, { catalogItemId: item.id, title: item.name, description: item.description ?? "", quantity: 1, unitPriceCents: item.unitPriceCents, discountBps: 0 }] })); };
  const save = async () => { if (!draft.clientId) return toast.error("Selecione um cliente."); if (!draft.title.trim()) return toast.error("Indique um título para a proposta."); const data = { ...draft, title: draft.title.trim(), validUntil: draft.validUntil ? new Date(`${draft.validUntil}T00:00:00`) : null, clientMessage: draft.clientMessage || null, internalNotes: draft.internalNotes || null, commercialTerms: { paymentTerms: draft.paymentTerms, downPayment: draft.downPayment, financingTerms: draft.financingTerms, commissionTerms: draft.commissionTerms, eligibilityCriteria: draft.eligibilityCriteria, catalogAttributes: draft.catalogAttributes }, items: draft.items }; try { if (id) await update.mutateAsync({ id, data }); else await create.mutateAsync(data); } catch (error) { toast.error(error instanceof Error ? error.message : "Não foi possível guardar a proposta."); } };

  if (id && detail.isLoading) return <DashboardLayout><div className="deco-panel p-10 text-center text-muted-foreground">A carregar o rascunho…</div></DashboardLayout>;
  if (id && detail.data?.proposal.state !== "draft") return <DashboardLayout><div className="deco-panel p-10 text-center"><p className="deco-eyebrow">Edição bloqueada</p><h1 className="deco-title mt-2 text-4xl">Esta proposta já não é um rascunho</h1><Button onClick={() => navigate(`/propostas/${id}`)} className="mt-6 rounded-none bg-primary text-primary-foreground">Ver proposta</Button></div></DashboardLayout>;
  return <DashboardLayout><section className="mx-auto max-w-7xl space-y-7"><header className="flex flex-col justify-between gap-5 border-b border-primary/30 pb-7 sm:flex-row sm:items-end"><div><Button variant="ghost" onClick={() => navigate(id ? `/propostas/${id}` : "/propostas")} className="-ml-3 mb-3 rounded-none text-primary hover:bg-primary/10 hover:text-primary"><ArrowLeft className="mr-2 h-4 w-4" />Voltar</Button><p className="deco-eyebrow">{id ? "Editar rascunho" : "Nova proposta"}</p><h1 className="deco-title mt-2 text-5xl sm:text-6xl">Compor proposta</h1></div><Button onClick={save} disabled={create.isPending || update.isPending} className="h-11 rounded-none bg-primary text-primary-foreground hover:bg-primary/85"><Save className="mr-2 h-4 w-4" />Guardar rascunho</Button></header>
    <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_20rem]"><div className="space-y-6"><div className="deco-panel grid gap-4 p-6 md:grid-cols-2"><div className="md:col-span-2"><p className="deco-eyebrow">Identificação</p><h2 className="deco-title mt-1 text-3xl">Destinatário e enquadramento</h2></div><label className="space-y-2 text-sm md:col-span-2">Título da proposta<Input value={draft.title} onChange={event => set("title", event.target.value)} placeholder="Ex.: Proposta de consultoria estratégica" className="rounded-none" /></label><label className="space-y-2 text-sm">Cliente<select value={draft.clientId} onChange={event => set("clientId", Number(event.target.value))} className="flex h-9 w-full border border-input bg-transparent px-3 text-sm"><option value={0}>Selecione um cliente</option>{clients.data?.filter(client => !client.archivedAt).map(client => <option key={client.id} value={client.id}>{client.companyName || client.contactName}</option>)}</select></label><label className="space-y-2 text-sm">Válida até<Input type="date" value={draft.validUntil} onChange={event => set("validUntil", event.target.value)} className="rounded-none" /></label><label className="flex items-center gap-3 text-sm md:col-span-2"><input type="checkbox" checked={draft.publicSharingEnabled} onChange={event => set("publicSharingEnabled", event.target.checked)} className="h-4 w-4 accent-primary" />Permitir visualização pelo link seguro do cliente</label></div>
      <div className="deco-panel p-6"><div className="flex flex-col justify-between gap-3 border-b border-primary/20 pb-4 sm:flex-row sm:items-end"><div><p className="deco-eyebrow">Itens de linha</p><h2 className="deco-title mt-1 text-3xl">Âmbito e valor</h2></div><select defaultValue="" onChange={event => { if (event.target.value) { addCatalogItem(Number(event.target.value)); event.currentTarget.value = ""; } }} className="h-9 border border-primary/40 bg-transparent px-3 text-sm text-foreground"><option value="">Adicionar do catálogo</option>{catalog.data?.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></div>
        <div className="mt-4 space-y-3">{!draft.items.length ? <p className="border border-dashed border-primary/30 p-6 text-center text-sm text-muted-foreground">Selecione produtos ou serviços a partir do catálogo.</p> : draft.items.map((item, index) => <div key={`${item.catalogItemId}-${index}`} className="grid gap-3 border border-primary/20 p-4 md:grid-cols-[minmax(0,1fr)_6rem_8rem_6rem_auto]"><div><Input value={item.title} onChange={event => updateLine(index, { title: event.target.value })} className="rounded-none font-medium" /><Input value={item.description} onChange={event => updateLine(index, { description: event.target.value })} placeholder="Descrição opcional" className="mt-2 rounded-none text-xs" /></div><label className="text-xs text-muted-foreground">Qtd.<Input type="number" min="0.001" step="0.001" value={item.quantity} onChange={event => updateLine(index, { quantity: Number(event.target.value) })} className="mt-1 rounded-none" /></label><label className="text-xs text-muted-foreground">Preço unit.<Input type="number" min="0" step="0.01" value={(item.unitPriceCents / 100).toFixed(2)} onChange={event => updateLine(index, { unitPriceCents: Math.round(Number(event.target.value) * 100) })} className="mt-1 rounded-none" /></label><label className="text-xs text-muted-foreground">Desc. %<Input type="number" min="0" max="100" step="0.01" value={(item.discountBps / 100).toFixed(2)} onChange={event => updateLine(index, { discountBps: Math.round(Number(event.target.value) * 100) })} className="mt-1 rounded-none" /></label><Button size="icon" variant="ghost" onClick={() => setDraft(current => ({ ...current, items: current.items.filter((_, position) => position !== index) }))} className="self-end rounded-none text-destructive hover:bg-destructive/10 hover:text-destructive"><Trash2 className="h-4 w-4" /></Button></div>)}</div></div>
      <div className="deco-panel grid gap-4 p-6 md:grid-cols-2"><div className="md:col-span-2"><p className="deco-eyebrow">Condições comerciais</p><h2 className="deco-title mt-1 text-3xl">Termos da negociação</h2></div><label className="space-y-2 text-sm md:col-span-2">Mensagem para o cliente<Textarea value={draft.clientMessage} onChange={event => set("clientMessage", event.target.value)} placeholder="Mensagem de acompanhamento apresentada no documento." className="min-h-24 rounded-none" /></label><label className="space-y-2 text-sm">Condições de pagamento<Textarea value={draft.paymentTerms} onChange={event => set("paymentTerms", event.target.value)} placeholder="Ex.: 30 dias após adjudicação." className="min-h-24 rounded-none" /></label><label className="space-y-2 text-sm">Entrada / sinal<Input value={draft.downPayment} onChange={event => set("downPayment", event.target.value)} placeholder="Ex.: 20% na adjudicação" className="rounded-none" /></label><label className="space-y-2 text-sm">Financiamento<Input value={draft.financingTerms} onChange={event => set("financingTerms", event.target.value)} placeholder="Ex.: crédito sujeito a aprovação" className="rounded-none" /></label><label className="space-y-2 text-sm">Comissões<Input value={draft.commissionTerms} onChange={event => set("commissionTerms", event.target.value)} placeholder="Ex.: incluídas no valor" className="rounded-none" /></label><label className="space-y-2 text-sm">Elegibilidade<Textarea value={draft.eligibilityCriteria} onChange={event => set("eligibilityCriteria", event.target.value)} placeholder="Critérios, documentos ou limitações aplicáveis." className="min-h-24 rounded-none" /></label><label className="space-y-2 text-sm">Atributos do catálogo<Textarea value={draft.catalogAttributes} onChange={event => set("catalogAttributes", event.target.value)} placeholder="Características, disponibilidade ou notas associadas aos itens." className="min-h-24 rounded-none" /></label><label className="space-y-2 text-sm md:col-span-2">Notas internas<Textarea value={draft.internalNotes} onChange={event => set("internalNotes", event.target.value)} placeholder="Nunca serão expostas no link público." className="min-h-24 rounded-none" /></label></div></div>
      <aside className="deco-panel h-fit p-6"><p className="deco-eyebrow">Resumo financeiro</p><h2 className="deco-title mt-1 text-3xl">Totais</h2><div className="mt-6 space-y-4 text-sm"><label className="flex items-center justify-between gap-3">Desconto global <Input type="number" min="0" max="100" step="0.01" value={(draft.globalDiscountBps / 100).toFixed(2)} onChange={event => set("globalDiscountBps", Math.round(Number(event.target.value) * 100))} className="w-20 rounded-none text-right" /></label><label className="flex items-center justify-between gap-3">IVA / imposto <Input type="number" min="0" max="100" step="0.01" value={(draft.taxRateBps / 100).toFixed(2)} onChange={event => set("taxRateBps", Math.round(Number(event.target.value) * 100))} className="w-20 rounded-none text-right" /></label><div className="border-t border-primary/25 pt-4"><div className="flex justify-between"><span className="text-muted-foreground">Subtotal</span><span>{money(totals.subtotal, draft.currency)}</span></div><div className="mt-2 flex justify-between"><span className="text-muted-foreground">Desconto</span><span>− {money(totals.discount, draft.currency)}</span></div><div className="mt-2 flex justify-between"><span className="text-muted-foreground">Imposto</span><span>{money(totals.tax, draft.currency)}</span></div><div className="mt-5 border-t border-primary/40 pt-4"><p className="deco-eyebrow">Total</p><p className="deco-title mt-1 text-3xl text-primary">{money(totals.total, draft.currency)}</p></div></div></div></aside></div>
  </section></DashboardLayout>;
}
